export const ERROR_CODES = [
  "VALIDATION_ERROR",
  "NO_FILE_PROVIDED",
  "INVALID_FILE_TYPE",
  "INVALID_FILE",
  "UNAUTHORIZED",
  "TOKEN_REVOKED",
  "FORBIDDEN",
  "NOT_FOUND",
  "PAYLOAD_TOO_LARGE",
  "STORAGE_LIMIT_EXCEEDED",
  "RATE_LIMITED",
  "INTERNAL_ERROR",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const ERROR_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  NO_FILE_PROVIDED: 400,
  INVALID_FILE_TYPE: 422,
  INVALID_FILE: 422,
  UNAUTHORIZED: 401,
  TOKEN_REVOKED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  PAYLOAD_TOO_LARGE: 413,
  STORAGE_LIMIT_EXCEEDED: 422,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
};
