/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthAudioRouteImport } from './routes/_auth/audio'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthDocsRouteImport } from './routes/_auth/docs'
import { Route as AuthFoldersRouteImport } from './routes/_auth/folders'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthUploadRouteImport } from './routes/_auth/upload'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthAdminAudioRouteImport } from './routes/_auth/admin/audio'
import { Route as AuthAdminLogsRouteImport } from './routes/_auth/admin/logs'
import { Route as AuthAdminSettingsRouteImport } from './routes/_auth/admin/settings'
import { Route as AuthAdminUsersIndexRouteImport } from './routes/_auth/admin/users.index'
import { Route as AuthAdminUsersIdRouteImport } from './routes/_auth/admin/users.$id'
import { Route as AuthAdminUsersNewRouteImport } from './routes/_auth/admin/users.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAudioRoute = AuthAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocsRoute = AuthDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFoldersRoute = AuthFoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUploadRoute = AuthUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminAudioRoute = AuthAdminAudioRouteImport.update({
  id: '/admin/audio',
  path: '/admin/audio',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminLogsRoute = AuthAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminSettingsRoute = AuthAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersIndexRoute = AuthAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersIdRoute = AuthAdminUsersIdRouteImport.update({
  id: '/admin/users/$id',
  path: '/admin/users/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersNewRoute = AuthAdminUsersNewRouteImport.update({
  id: '/admin/users/new',
  path: '/admin/users/new',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audio': typeof AuthAudioRoute
  '/dashboard': typeof AuthDashboardRoute
  '/docs': typeof AuthDocsRoute
  '/folders': typeof AuthFoldersRoute
  '/profile': typeof AuthProfileRoute
  '/upload': typeof AuthUploadRoute
  '/admin/audio': typeof AuthAdminAudioRoute
  '/admin/logs': typeof AuthAdminLogsRoute
  '/admin/settings': typeof AuthAdminSettingsRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/admin/users/$id': typeof AuthAdminUsersIdRoute
  '/admin/users/new': typeof AuthAdminUsersNewRoute
  '/admin/users/': typeof AuthAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audio': typeof AuthAudioRoute
  '/dashboard': typeof AuthDashboardRoute
  '/docs': typeof AuthDocsRoute
  '/folders': typeof AuthFoldersRoute
  '/profile': typeof AuthProfileRoute
  '/upload': typeof AuthUploadRoute
  '/admin/audio': typeof AuthAdminAudioRoute
  '/admin/logs': typeof AuthAdminLogsRoute
  '/admin/settings': typeof AuthAdminSettingsRoute
  '/admin': typeof AuthAdminIndexRoute
  '/admin/users/$id': typeof AuthAdminUsersIdRoute
  '/admin/users/new': typeof AuthAdminUsersNewRoute
  '/admin/users': typeof AuthAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/audio': typeof AuthAudioRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/docs': typeof AuthDocsRoute
  '/_auth/folders': typeof AuthFoldersRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/upload': typeof AuthUploadRoute
  '/_auth/admin/audio': typeof AuthAdminAudioRoute
  '/_auth/admin/logs': typeof AuthAdminLogsRoute
  '/_auth/admin/settings': typeof AuthAdminSettingsRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/admin/users/$id': typeof AuthAdminUsersIdRoute
  '/_auth/admin/users/new': typeof AuthAdminUsersNewRoute
  '/_auth/admin/users/': typeof AuthAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audio'
    | '/dashboard'
    | '/docs'
    | '/folders'
    | '/profile'
    | '/upload'
    | '/admin/audio'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin/'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audio'
    | '/dashboard'
    | '/docs'
    | '/folders'
    | '/profile'
    | '/upload'
    | '/admin/audio'
    | '/admin/logs'
    | '/admin/settings'
    | '/admin'
    | '/admin/users/$id'
    | '/admin/users/new'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/audio'
    | '/_auth/dashboard'
    | '/_auth/docs'
    | '/_auth/folders'
    | '/_auth/profile'
    | '/_auth/upload'
    | '/_auth/admin/audio'
    | '/_auth/admin/logs'
    | '/_auth/admin/settings'
    | '/_auth/admin/'
    | '/_auth/admin/users/$id'
    | '/_auth/admin/users/new'
    | '/_auth/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/audio': {
      id: '/_auth/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AuthAudioRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/docs': {
      id: '/_auth/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthDocsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/folders': {
      id: '/_auth/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AuthFoldersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/upload': {
      id: '/_auth/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthUploadRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/audio': {
      id: '/_auth/admin/audio'
      path: '/admin/audio'
      fullPath: '/admin/audio'
      preLoaderRoute: typeof AuthAdminAudioRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/logs': {
      id: '/_auth/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthAdminLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/settings': {
      id: '/_auth/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthAdminSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users/': {
      id: '/_auth/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthAdminUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users/$id': {
      id: '/_auth/admin/users/$id'
      path: '/admin/users/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AuthAdminUsersIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users/new': {
      id: '/_auth/admin/users/new'
      path: '/admin/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AuthAdminUsersNewRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAudioRoute: typeof AuthAudioRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthDocsRoute: typeof AuthDocsRoute
  AuthFoldersRoute: typeof AuthFoldersRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthUploadRoute: typeof AuthUploadRoute
  AuthAdminAudioRoute: typeof AuthAdminAudioRoute
  AuthAdminLogsRoute: typeof AuthAdminLogsRoute
  AuthAdminSettingsRoute: typeof AuthAdminSettingsRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthAdminUsersIdRoute: typeof AuthAdminUsersIdRoute
  AuthAdminUsersNewRoute: typeof AuthAdminUsersNewRoute
  AuthAdminUsersIndexRoute: typeof AuthAdminUsersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAudioRoute: AuthAudioRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthDocsRoute: AuthDocsRoute,
  AuthFoldersRoute: AuthFoldersRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthUploadRoute: AuthUploadRoute,
  AuthAdminAudioRoute: AuthAdminAudioRoute,
  AuthAdminLogsRoute: AuthAdminLogsRoute,
  AuthAdminSettingsRoute: AuthAdminSettingsRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthAdminUsersIdRoute: AuthAdminUsersIdRoute,
  AuthAdminUsersNewRoute: AuthAdminUsersNewRoute,
  AuthAdminUsersIndexRoute: AuthAdminUsersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
